// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test, console} from "forge-std/Test.sol";
import {RootPay} from "../../src/RootPay.sol";
import {MockERC20} from "../mocks/MockERC20.sol";

contract BaseTestHelper is Test {
    // -------------------------------------------------------------------------
    // Keys and Addresses
    // -------------------------------------------------------------------------

    uint256 constant PAYER1PK = 1;
    uint256 constant PAYER2PK = 2;
    uint256 constant PAYEE1PK = 3;
    uint256 constant PAYEE2PK = 4;
    uint256 constant OWNERPK = 5;
    uint256 constant RELAYERPK = 6;

    address public immutable PAYER;
    address public immutable PAYER2;
    address public immutable PAYEE;
    address public immutable PAYEE2;
    address public immutable OWNER;
    address public immutable RELAYER;

    // -------------------------------------------------------------------------
    // Token Addresses
    // -------------------------------------------------------------------------

    address public constant NATIVE_TOKEN = address(0);
    MockERC20 public erc20;

    // -------------------------------------------------------------------------
    // Channel Timing Constants
    // -------------------------------------------------------------------------

    // Merchant unlock: must pass this many blocks before merchant can redeem
    uint64 public constant MERCHANT_DURATION = 100;

    // Payer reclaim: must be >= 1.1 * MERCHANT_DURATION to pass validation
    // 100 * 1.1 = 110, so 200 gives comfortable buffer
    uint64 public constant RECLAIM_DELAY = 200;

    // -------------------------------------------------------------------------
    // Merkle Tree Constants
    // -------------------------------------------------------------------------

    uint16 public constant DEFAULT_TREE_SIZE = 512; // Base tree size for standard tests
    uint16 public constant LARGE_TREE_SIZE = 4096; // 2^12  // For stress / boundary tests

    // -------------------------------------------------------------------------
    // Financial Constants
    // -------------------------------------------------------------------------

    uint256 public constant INITIAL_BALANCE = 100 ether;
    uint256 public constant DEPOSIT_AMOUNT = 10 ether;

    // -------------------------------------------------------------------------
    // Contract Under Test
    // -------------------------------------------------------------------------

    RootPay public rootPay;

    // -------------------------------------------------------------------------
    // Constructor
    // -------------------------------------------------------------------------

    constructor() {
        PAYER = vm.addr(PAYER1PK);
        PAYER2 = vm.addr(PAYER2PK);
        PAYEE = vm.addr(PAYEE1PK);
        PAYEE2 = vm.addr(PAYEE2PK);
        OWNER = vm.addr(OWNERPK);
        RELAYER = vm.addr(RELAYERPK);
    }

    // -------------------------------------------------------------------------
    // Setup
    // -------------------------------------------------------------------------

    function setUp() public virtual {
        rootPay = new RootPay();
        erc20 = new MockERC20("Mock Token", "MKT");

        // Fund native token balances
        vm.deal(PAYER, INITIAL_BALANCE);
        vm.deal(PAYER2, INITIAL_BALANCE);
        vm.deal(PAYEE, INITIAL_BALANCE);
        vm.deal(RELAYER, INITIAL_BALANCE);

        // Mint and approve ERC-20 balances
        erc20.mint(PAYER, INITIAL_BALANCE);
        erc20.mint(PAYER2, INITIAL_BALANCE);

        vm.prank(PAYER);
        erc20.approve(address(rootPay), type(uint256).max);

        vm.prank(PAYER2);
        erc20.approve(address(rootPay), type(uint256).max);
    }

    // -------------------------------------------------------------------------
    // Channel Creation Helpers
    // -------------------------------------------------------------------------

    /**
     * @dev Creates a native currency channel with default parameters.
     * Caller must pass a merkleRoot (generated by MerkleHelper in actual tests).
     */
    function _createNativeChannel(address payer, address merchant, bytes32 merkleRoot, uint16 treeSize) internal {
        vm.prank(payer);
        rootPay.createChannel{value: DEPOSIT_AMOUNT}(
            merchant, NATIVE_TOKEN, merkleRoot, DEPOSIT_AMOUNT, treeSize, MERCHANT_DURATION, RECLAIM_DELAY
        );
    }

    /**
     * @dev Creates an ERC-20 channel with default parameters.
     */
    function _createERC20Channel(address payer, address merchant, bytes32 merkleRoot, uint16 treeSize) internal {
        vm.prank(payer);
        rootPay.createChannel(
            merchant, address(erc20), merkleRoot, DEPOSIT_AMOUNT, treeSize, MERCHANT_DURATION, RECLAIM_DELAY
        );
    }

    // -------------------------------------------------------------------------
    // Block Advancement Helpers
    // -------------------------------------------------------------------------

    /**
     * @dev Advances past the merchant unlock block so redemption is permitted.
     */
    function _advancePastMerchantWindow() internal {
        vm.roll(block.number + MERCHANT_DURATION + 1);
    }

    /**
     * @dev Advances past the payer reclaim block so reclaim is permitted.
     */
    function _advancePastReclaimWindow() internal {
        vm.roll(block.number + RECLAIM_DELAY + 1);
    }

    // -------------------------------------------------------------------------
    // Assertion Helpers
    // -------------------------------------------------------------------------

    /**
     * @dev Asserts that a channel exists in storage with the expected core fields.
     */
    function _assertChannelExists(
        address payer,
        address merchant,
        address token,
        bytes32 expectedRoot,
        uint16 expectedTreeSize
    ) internal view {
        (address storedToken, bytes32 storedRoot, uint256 storedAmount, uint16 storedTreeSize,,) =
            rootPay.channelsMapping(payer, merchant, token);

        assertEq(storedToken, token, "token mismatch");
        assertEq(storedRoot, expectedRoot, "merkleRoot mismatch");
        assertEq(storedAmount, DEPOSIT_AMOUNT, "amount mismatch");
        assertEq(storedTreeSize, expectedTreeSize, "treeSize mismatch");
    }

    /**
     * @dev Asserts that a channel has been deleted from storage.
     */
    function _assertChannelDeleted(address payer, address merchant, address token) internal view {
        (,, uint256 storedAmount,,,) = rootPay.channelsMapping(payer, merchant, token);
        assertEq(storedAmount, 0, "channel should be deleted");
    }

    /**
     * @dev Computes the expected merchant payout for a given leafIndex and treeSize.
     * Mirrors the contract formula: (leafIndex + 1) * amount / treeSize
     */
    function _expectedMerchantPayout(uint16 leafIndex, uint16 treeSize, uint256 amount)
        internal
        pure
        returns (uint256)
    {
        return (amount * (uint256(leafIndex) + 1)) / treeSize;
    }
}
